### PR TITLE
Added docker support

### PR DESCRIPTION
**Pull request by tomercagan**
Added required files to run the application on top of docker.
Based on the manual installation instructions but modified slightly to run on Centos.

### CODE REVIEW

**Comment by rpgove** [comment]
Thanks for submitting this! Sorry for the delay.

Does this work for you? I'm having a couple problems.

1. It gives me errors until I create the mongo/data and mongo/configdb directories. It would be nice if  the README gave instructions to create the directories. It would be even better if users didn't have to manually create these.

2. After I got it running, I can't import any of the example policies. V3SPA gives me import errors (e.g. can't find the binary policy).

**Comment by tomercagan** [comment]
Hi,
As for (1) I will make the required changes. The idea there is that the data is stored on the host.

As for (2) - it fails for me as well, I couldn't get it running with either of the example binary policies, only with source one. I want sure whether it works at all and since all the installation steps go through without any errors, I assumed it doesn't work.

I'd be happy to get it running fully if someone can point me as to what the use might be. I didn't see anything I could use in system logs and didn't have time to go deeply into debugging the application itself

**Comment by rpgove** [comment]
For (2), I can't get any policies to import (binary or source). This is true for Vagrant and Docker. It looks like there's some issue with Lobster. I'm not sure why it can't import binary policies. I don't have time to debug either issue, though.

If you can fix (1), then I'll accept your PR and open a separate issue for (2).

**Comment by tomercagan** [comment]
Hi,

I discussed this with a friend who's more versed with Docker and he said there's not much to do.
There's an option to possibly add "run-docker" to the make file but I am not sure whether it is a good option (and whether I will have the time to do it now).
Lets go with the additional information in the README file and if there are issues/complains we will look into automating the mongo storage.

**Pull request merged**
